---
- name: Test NetBox modules
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - netbox.netbox

  vars:
    netbox_url: "http://10.0.0.53:8000"
    netbox_token: "nbt_WwYJvdiKYpbn.6LsJU1PDzB2iWdJJwfOR9iO1TDZzJc1V8rJCswC1"

  tasks:

    # -------------------------
    # CREATE CABLE
    # -------------------------
    - name: Create cable within NetBox with only required information
      netbox.netbox.netbox_cable:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"

        data:
          termination_a_type: dcim.interface
          termination_a:
            device: Test Nexus Child One
            name: Ethernet2/2

          termination_b_type: dcim.interface
          termination_b:
            device: Test Nexus Child Two
            name: Ethernet2/1

        state: present


    # -------------------------
    # UPDATE CABLE
    # -------------------------
    - name: Update cable with other fields
      netbox.netbox.netbox_cable:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"

        data:
          termination_a_type: dcim.interface
          termination_a:
            device: Test Nexus Child One
            name: Ethernet2/2

          termination_b_type: dcim.interface
          termination_b:
            device: Test Nexus Child Two
            name: Ethernet2/1

          type: mmf-om4
          status: planned
          label: label123
          color: abcdef
          length: 30
          length_unit: m
          tags:
            - foo

        state: present


    # -------------------------
    # DELETE CABLE
    # -------------------------
    - name: Delete cable within NetBox
      netbox.netbox.netbox_cable:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"

        data:
          termination_a_type: dcim.interface
          termination_a:
            device: Test Nexus Child One
            name: Ethernet2/2

          termination_b_type: dcim.interface
          termination_b:
            device: Test Nexus Child Two
            name: Ethernet2/1

        state: absent
